// <auto-generated />
using System;
using AssetManagementSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetManagementSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251016123323_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("AssetManagementSystem.Entity.Entities.AssetModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActivated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("AssetManagementSystem.Entity.Entities.DepartmentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ca165926-a659-4e68-b36b-bd0833a35b41"),
                            CreatedAt = new DateTime(2025, 10, 16, 12, 33, 23, 65, DateTimeKind.Utc).AddTicks(7418),
                            CreatedBy = "System",
                            Description = "Handles software, hardware, and infrastructure-related assets.",
                            IsActive = true,
                            Name = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("fedd83c2-cd3a-47ff-aa2e-d4766ce07c29"),
                            CreatedAt = new DateTime(2025, 10, 16, 12, 33, 23, 65, DateTimeKind.Utc).AddTicks(7423),
                            CreatedBy = "System",
                            Description = "Manages employee relations and administrative equipment.",
                            IsActive = true,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = new Guid("79ca0749-c8cf-4296-8775-36d4d3b93173"),
                            CreatedAt = new DateTime(2025, 10, 16, 12, 33, 23, 65, DateTimeKind.Utc).AddTicks(7426),
                            CreatedBy = "System",
                            Description = "Responsible for accounting systems, finance tools, and related devices.",
                            IsActive = true,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = new Guid("499e724d-9782-4f15-ab6b-9acf7d6247ab"),
                            CreatedAt = new DateTime(2025, 10, 16, 12, 33, 23, 65, DateTimeKind.Utc).AddTicks(7430),
                            CreatedBy = "System",
                            Description = "Oversees logistics, facilities, and maintenance assets.",
                            IsActive = true,
                            Name = "Operations"
                        },
                        new
                        {
                            Id = new Guid("4c26af81-dc33-43c0-91c5-4ecc61c9407e"),
                            CreatedAt = new DateTime(2025, 10, 16, 12, 33, 23, 65, DateTimeKind.Utc).AddTicks(7436),
                            CreatedBy = "System",
                            Description = "Manages branding equipment, digital tools, and promotional materials.",
                            IsActive = true,
                            Name = "Marketing"
                        });
                });

            modelBuilder.Entity("AssetManagementSystem.Entity.Entities.TagModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.HasIndex("MacAddress")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("AssetManagementSystem.Entity.Entities.AssetModel", b =>
                {
                    b.HasOne("AssetManagementSystem.Entity.Entities.DepartmentModel", "Department")
                        .WithMany("Assets")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AssetManagementSystem.Entity.Entities.TagModel", b =>
                {
                    b.HasOne("AssetManagementSystem.Entity.Entities.AssetModel", "Asset")
                        .WithOne("Tag")
                        .HasForeignKey("AssetManagementSystem.Entity.Entities.TagModel", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("AssetManagementSystem.Entity.Entities.AssetModel", b =>
                {
                    b.Navigation("Tag");
                });

            modelBuilder.Entity("AssetManagementSystem.Entity.Entities.DepartmentModel", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
