// <auto-generated />
using System;
using AssetManagementSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetManagementSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251105100541_user")]
    partial class user
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("AssetManagementSystem.Entity.Entities.AssetModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActivated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("AssetManagementSystem.Entity.Entities.DepartmentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1881f2a5-39e5-4db3-88bb-9abecc88a237"),
                            CreatedAt = new DateTime(2025, 11, 5, 10, 5, 40, 617, DateTimeKind.Utc).AddTicks(5346),
                            CreatedBy = "System",
                            Description = "Handles software, hardware, and infrastructure-related assets.",
                            IsActive = true,
                            Name = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("3ec1410a-d735-4516-a3b5-235b905e8b58"),
                            CreatedAt = new DateTime(2025, 11, 5, 10, 5, 40, 617, DateTimeKind.Utc).AddTicks(5351),
                            CreatedBy = "System",
                            Description = "Manages employee relations and administrative equipment.",
                            IsActive = true,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = new Guid("0b9c7db2-93d8-4ddd-9842-89bfa0cf2d76"),
                            CreatedAt = new DateTime(2025, 11, 5, 10, 5, 40, 617, DateTimeKind.Utc).AddTicks(5354),
                            CreatedBy = "System",
                            Description = "Responsible for accounting systems, finance tools, and related devices.",
                            IsActive = true,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = new Guid("8b871c99-f8d3-4326-bff5-15cade7e1a6a"),
                            CreatedAt = new DateTime(2025, 11, 5, 10, 5, 40, 617, DateTimeKind.Utc).AddTicks(5358),
                            CreatedBy = "System",
                            Description = "Oversees logistics, facilities, and maintenance assets.",
                            IsActive = true,
                            Name = "Operations"
                        },
                        new
                        {
                            Id = new Guid("ea12d78f-f555-4d26-b289-5da3bc24ec29"),
                            CreatedAt = new DateTime(2025, 11, 5, 10, 5, 40, 617, DateTimeKind.Utc).AddTicks(5364),
                            CreatedBy = "System",
                            Description = "Manages branding equipment, digital tools, and promotional materials.",
                            IsActive = true,
                            Name = "Marketing"
                        });
                });

            modelBuilder.Entity("AssetManagementSystem.Entity.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2df42591-a865-40ee-817d-c2eaf6891ca2"),
                            CreatedAt = new DateTime(2025, 11, 5, 10, 5, 40, 617, DateTimeKind.Utc).AddTicks(2965),
                            CreatedBy = "System",
                            IsActive = true,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("0c9e30eb-2775-46b8-8fb3-f14a6e808586"),
                            CreatedAt = new DateTime(2025, 11, 5, 10, 5, 40, 617, DateTimeKind.Utc).AddTicks(2970),
                            CreatedBy = "System",
                            IsActive = true,
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("AssetManagementSystem.Entity.Entities.TagModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.HasIndex("MacAddress")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("AssetManagementSystem.Entity.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHashed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefereshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RefereshTokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RoleID")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AssetManagementSystem.Entity.Entities.AssetModel", b =>
                {
                    b.HasOne("AssetManagementSystem.Entity.Entities.DepartmentModel", "Department")
                        .WithMany("Assets")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AssetManagementSystem.Entity.Entities.TagModel", b =>
                {
                    b.HasOne("AssetManagementSystem.Entity.Entities.AssetModel", "Asset")
                        .WithOne("Tag")
                        .HasForeignKey("AssetManagementSystem.Entity.Entities.TagModel", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("AssetManagementSystem.Entity.Entities.User", b =>
                {
                    b.HasOne("AssetManagementSystem.Entity.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AssetManagementSystem.Entity.Entities.AssetModel", b =>
                {
                    b.Navigation("Tag");
                });

            modelBuilder.Entity("AssetManagementSystem.Entity.Entities.DepartmentModel", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("AssetManagementSystem.Entity.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
